services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - .:/vue3-bootstrap5-composables:cached
    ports:
      - 5173:5173
    tty: true
