services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
      args:
        - WORKDIR_NAME=${DEVELOPMENT_PACKAGE_NAME}
    volumes:
      - .:/${DEVELOPMENT_PACKAGE_NAME}:cached
    ports:
      - 5173:5173
    tty: true
    environment:
      - NPM_CONFIG_USERCONFIG=/${DEVELOPMENT_PACKAGE_NAME}/.npmrc
